# Privacidad y Seguridad en Internet 

## Introducción

En estos últimos años hemos podido ver como la evolución de las IT (Tecnologías de la información) y el paso de la Web 1.0 a la Web 2.0, nos ha permitido a muchos de nosotros como usuarios interactuar los unos con los otros subiendo y compartiendo todo tipo de contenidos. La aparición de las Redes sociales ha traído con ellas, la posibilidad de  publicar fotos, videos, información, comentarios, reseñas, etc.  a través de cualquier dispositivo, ya sea un PC, tablet o smartphone. Y no solo eso, sino que además, también nos ha abierto un amplio abanico de posibilidades con las que podemos  gestionar cuentas bancarias, hacer compras online, trámites telemáticos y un sinfín  de gestiones que hasta hace tan solo unos años atrás eran difíciles de imaginar.

Además, a todo lo anterior se añade este nuevo escenario hacia la web 3.0 en el que ha aumentado la exposición a la superficie digital y donde el incremento exponencial de ciberdelincuencia parece no tener freno. Es por ello que bajo estas circunstancias es cuando más debemos aprender y mejorar las destrezas digitales y hacerlas compatibles con un uso responsable, respetuoso y crítico de la tecnología, desarrollando capacidades digitales en las que  un entorno, seguro, privado y sostenibles que garantice el bienestar social sea posible.

Como consecuencia de ello, el enorme conglomerado de información sensible que se encuentra disponible en internet, hace que nosotros como usuarios estemos en el punto de mira de ciberdelincuentes y expuestos a todo tipo de ciberataques. En esta línea, este manual contribuye a enseñarte, aconsejarte y proveerte de herramientas necesarias para  prevenir, evitar y paliar  en la medida de lo posible todos los  riesgos y peligros a los que estamos expuestos  en nuestro uso diario de las tecnologías.

Por lo tanto, en lo sucesivo iras viendo el porqué de la importancia de velar de manera activa por tu privacidad y seguridad en internet haciendo una buena gestión de éstas. También te ayudará a conocer y reconocer la amplia lista de ciberdelitos que actualmente están más extendidos. 

En estas [estadísticas](https://oedi.es/estadisticas/) publicadas por el  Observatorio Español de Delitos informáticos [@oedi] puedes ver el porqué de cuidar tu privacidad y seguridad en internet. En ellas se expone una  exhaustiva lista de ciberdelitos  y sus recurrencias cronológicas.

## Privacidad 

La privacidad es aquello que se lleva a cabo en un ámbito reservado; en Internet podría entenderse como el  control que ejercemos sobre nuestra información  para limitar la cantidad de personas autorizadas a verla, así como la cantidad de contenido expuesto. Esto incluye datos personales, fotografías, documentos, etc. 

Internet es una herramienta que nos permite la interacción entre dos o más personas. Siendo ejemplo de los anteriores sitios como Facebook y Twitter, Redes Sociales en donde las personas pueden compartir públicamente opiniones, noticias, sentimientos, ideas, fotografías, videos, etc. Por ello es necesario considerar que Internet es un espacio abierto al mundo, por lo tanto, cualquier acción que se haga va a tener un impacto global y permanente. Por ejemplo, imagina una publicación de la cual puedas arrepentirte (como una fotografía u opinión) no solo podrá ser vista por millones de usuarios, sino que también será prácticamente imposible de borrar completamente de la red .

También puede resultar peligroso publicar datos que puedan identificarte, como la dirección, teléfonos, lugar de estudio o trabajo, días de vacaciones, etc. Esto puede resultar todavía más complicado si posees una gran lista de amigos a los que no conoces  personalmente. 

Por todo lo que se ha mencionado en éstas últimas líneas, es de suma importancia que antes de publicar algo, pienses en las consecuencias que puede conllevar divulgar información sensible en sitios públicos y de los cuales no siempre se tiene un control directo [@privacidad].

## Seguridad

La seguridad en internet son todas aquellas precauciones que son tomadas para proteger todos los dispositivos informáticos, así como la red de internet que pueden ser afectados por delincuentes cibernéticos. Además de ser una rama de la seguridad informática que se dedica a identificar y prevenir todas las amenazas que afectan a la red de redes, siendo una de las herramientas más conocidas los antivirus [@seguridad].

Entre los peligros más habituales de no hacer un buen uso de la seguridad en la red, nos encontramos, robo de datos bancarios o personales, virus informáticos, phishing, spam, etc. Pero estos no son los únicos riesgos que asechan en internet, como verás más adelante.

## RGPD (Reglamento general de protección de datos)

El Reglamento General de Protección de Datos (RGPD) es el reglamento europeo relativo a la protección de las personas físicas en lo que respecta al tratamiento de sus datos personales y a la libre circulación de estos datos. Entró en vigor el 25 de mayo de 2016 y fue de aplicación el 25 de mayo de 2018, dos años durante los cuales las empresas, las organizaciones, los organismos y las instituciones han debido ir adaptándose para su cumplimiento. Es una normativa a nivel de la Unión Europea, por lo que cualquier empresa de la unión, o aquellas empresas que tengan negocios en ésta y que manejen información personal de cualquier tipo deberán acogerse a la misma [@WIKI-rgpd].

En el pasado, el uso de datos era obtenido por omisión, en estos momentos para estar seguros de cumplir con el RGPD se ha de obtener el consentimiento inequívoco o expreso por parte del usuario.

Paralela a la RGPD europea existe una a nivel de España llamada Ley orgánica de protección de datos y garantía de los derechos digitales, recogida en el BOE [Boletín Oficial del Estado](https://www.boe.es/buscar/doc.php?id=BOE-A-2018-16673) y cuyo objeto es también garantizar y proteger las libertades públicas y los derechos fundamentales de las personas físicas y en especial, su honor e integridad personal y familiar.

Entre los aspectos más significativos del RGPD cabe destacar los siguientes:

- Derecho a la portabilidad de los datos: Te da el derecho de solicitar al responsable de tus datos el traspaso de éstos a otra entidad o responsable. Un ejemplo claro es la conocida portabilidad en el mundo de la telefonía que hacen que tus datos puedas ser cedidos de una compañía a otra.

- Derecho a la supresión: Es una versión mejorada de la solicitud de cancelación o eliminación de tus datos.

- Derecho al olvido: Te da derecho a solicitar al responsable de tus datos la supresión o eliminación de éstos, pero con un enfoque más estrecho con el ámbito digital. Desde el servicio ofrecido por [AEPD](https://www.aepd.es/es/areas-de-actuacion/internet-y-redes-sociales/derecho-al-olvido) puedes acceder a los enlaces donde solicitar el derecho al olvido en [Google](https://www.google.com/webmasters/tools/legal-removal-request?complaint_type=rtbf&visit_id=637490694757326412-3626204680&hl=es&rd=1), [Bing](https://www.bing.com/webmaster/tools/eu-privacy-request), [Yahoo](https://es.ayuda.yahoo.com/kb/Solicitud-para-bloquear-resultados-de-b%C3%BAsqueda-en-Yahoo-Search-Recursos-para-Residentes-Europeos-sln28252.html?guccounter=1&guce_referrer=aHR0cHM6Ly93d3cuYWVwZC5lcy8&guce_referrer_sig=AQAAAIRquvv_VPnIiAOniwOvZi_iVodzBg6yn2C0sGApxESxJWBR6RMqeNq89qO01lmI0UdIKSr3ivLxST8cTDrgIMQRF9FIda60jZQ16f8q85f-eqLvvviA02B_fephtV40QIGV7aQ8Uw0M7f_poDUONOrmeKQzbahKvnuKZCoBDBFQ), aunque desde estos últimos enlaces ya puedes acceder directamente.

## Aviso legal, política de privacidad y política de cookies

Si una web va a realizar transacciones comerciales de la naturaleza que sea, va a gestionar datos de usuarios o hacer uso de cookies, ha de tener a disposición del usuario las políticas que más abajo se detallan. Todas estas políticas están recogidas en el RGPD del apartado anterior. Sin embargo, para documentarlo con terminología más cotidiana, en este apartado nos hemos apoyado en la sección de derecho digital de la compañía IONOS by 1&1 en su división IONOS Guía Digital.

- Aviso Legal: Se trata de un documento donde se recogen tanto el cumplimiento por parte de la entidad o empresa, conforme a las leyes vigentes en el desarrollo de su actividad, así como los datos referentes a los administradores de la misma.

  Todo proyecto de base digital u online con ánimo de lucro, ya sea a través de modelos de patrocinio, publicitarios o compra-venta  de productos o servicios, requieren de un aviso legal visiblemente expuesto y a disposición de todos los usuarios. Este requerimiento está recogido en la legislación española en la Ley 34/2002 de Servicios de la Sociedad de la Información y el Comercio Electrónico [@IONOS-legal].

- Política de privacidad: El reglamento general de Protección de Datos de carácter personal, establece que cualquier página web que incluya un formulario de carácter personal que deban rellenar los usuarios, que incluya un correo de contacto o utilice las redes sociales desde las cuales se puede obtener información de los usuarios, está obligada a disponer de una política de privacidad [@IONOS-privacidad].

  La política de privacidad se creó con la finalidad de proteger y preservar los derechos del espacio privado de las personas. 

- Política de cookies: Una cookie es una pequeña información enviada por un sitio web y almacenado en el navegador del usuario, de manera que el sitio web puede consultar la actividad previa del navegador. Su propósito principal es identificar al usuario almacenando su historial de actividad en un sitio web específico, de manera que se le pueda ofrecer el contenido más apropiado según sus hábitos [@IONOS-cookies].

  Toda web que haga uso de cookies está obligada ponerlo en conocimiento de los usuarios y a solicitar su aceptación.
  
  Con respecto a la legislación de la Unión Europea sobre el consentimiento de las cookies debes saber que dicha ley dicta que los usuarios de internet deben tener la opción de poder rechazarlas, sin que por ello éste se vea perjudicado en su navegación. Esto nos lleva a señalar que el problema está en que la mayoría de los sitios web no lo cumplen. Normalmente tú como usuario en una mayor parte de las veces solo te vas a encontrar con  la opción de aceptar todas las cookies o rechazarlas, en otros casos con otra opción más confusa y compleja de manejar la configuración de estás. Y en la inmensa mayoría de las ocasiones no te vas a encontrar con esa alternativa que te brinda la ley de poder rechazarlas [@GEN-rechazar-cookies].
  
## Derechos ARCO

Los derechos ARCO  (Acceso, Rectificación, Cancelación y Oposición), están regulados por la Ley Orgánica de Protección de Datos y Garantía de Derechos Digitales, que has podido ver en un apartado anterior. 

- Derecho al acceso: Te da derecho a conocer el uso que la entidad o responsable de tus datos está haciendo de ellos.

- Derecho a la rectificación: Te da derecho a solicitar la rectificación de tus datos.

- Derecho a la cancelación: Te da derecho a solicitar la supresión de los datos que resulten inadecuados o excesivos.

- Derecho a la oposición: Te da derecho a oponerte al tratamiento de sus datos personales o el cese de éstos.

Para poder ejercer estos derechos solo basta con solicitarlo a la parte responsable de tus datos, aportando fotocopia del DNI o documento equivalente, la petición que se solicita, la dirección a efectos de notificaciones y los documentos que acreditan la petición que se formula [@arco].

