# Tu yo digital

##  Toma consciencia de tu yo digital

En esta sociedad actual, tecnológica y digitalizada, de la que todos en mayor o menor medida formamos parte, debemos tener siempre presente que la forma en que desarrollamos nuestra personalidad, creamos nuestras relaciones sociales o gestionamos nuestra economía, nos lleva a definir nuestra imagen de marca y reputación digital.

En la esfera digital todas y cada una de nuestras acciones tendrá una repercusión directa en lo que el resto va a percibir sobre nosotros y por ende a definir quiénes somos, tanto desde una perspectiva personal, profesional como social creando constantemente y a veces casi de manera imperceptible nuestra identidad digital. Es por ello que no debes perder el foco y entender que esto va a contribuir y afectar a todas las capas de tu yo analógico.

Por lo tanto, en este nuevo escenario hacia la web 3.0 en la que ha aumentado la exposición a la superficie digital, y en el que el incremento exponencial de la ciberdelincuencia parece no tener freno, debes aprender y mejorar la experiencia digital y hacerla compatible con un uso responsable, respetuoso, crítico y creativo de la tecnología. Y a su vez desarrollar capacidades digitales que propicien un progreso inclusivo, seguro, privado y sostenibles que garantice el bienestar social.

## Metadatos

Los metadatos pueden ser descritos de varias formas posibles, pero de forma resumida son un conjunto de datos que proporciona información de un recurso. Datos como pueden ser un archivo de imagen o un documento de texto, siendo algunos de estos metadatos la fecha de creación, la de última modificación o la resolución en el caso de una imagen [@WIKI-meta].

La función principal de los metadatos es la de ampliar con información adicional la contenida en el recurso del que forman parte con el fin de mejorar la calidad y efectividad de las búsquedas realizadas, no solo a la hora de realizar una búsqueda de un archivo perdido en nuestro sistema operativo, sino que esto afecta incluso al posicionamiento web.

En ciertas ocasiones estos datos pueden provocar problemas, algunos de ellos de seguridad y privacidad como puede ocurrir por ejemplo por alguno de los dos motivos siguientes:

- Suele ocurrir que algunas cámaras fotográficas incluyan las coordenadas geográficas desde las que se realiza la fotografía entre los metadatos en los archivos de imágenes, pudiéndose localizar la posición en la que la imagen fue tomada. Esto es lo que se conoce como [Geoetiquetado](https://es.wikipedia.org/wiki/Geoetiquetado).

- Puede determinarse la versión del software con la que fue guardado un archivo, por lo que si trabajas en una empresa y no tienes la licencia de dicho programa, los metadatos pueden generarte problemas.

- La longitud de los mensajes, el autor, la localización, las fechas, la hora, etc. identifican patrones de comportamientos, hábitos, relaciones y detalles personales. Todos estos datos son denominados el petróleo del siglo XXI [@OSI-petroleo-S-XXI].

Para que puedas hacer una valoración de por que a todos los datos personales se les denominan el petróleo del siglo XXI, visita la siguiente infografía de [cuál es el valor de tus datos en la red](https://www.osi.es/sites/default/files/images/concienciacion/c15-pdf-infografia-ciberdelincuentes_reyes.pdf).

## Huella digital o reputación online

Eres lo que publicas, lo que compartes, con quién te relacionas e incluso lo que visitas desde tus dispositivos y todo este rastro es lo que compone la huella digital. 

En otras palabras, la huella digital o reputación online es la fama o prestigio que una persona o una empresa tiene en el mundo digital. Realmente la reputación digital no difiere mucho de la reputación tradicional, ya que en cierto modo ambas están conectadas, por lo que deben ser coherente la una con la otra.

También se puede denominar la identidad digitad como el conjunto formado por:

- Información que nosotros mismos publicamos.

- Información que compartimos de otros usuarios.

- Aquella información que existe en Internet sobre nosotros.

Cabe destacar que la variante digital ha tomado gran importancia, ya que cuando una persona o compañía quiere saber de ti, uno de los mecanismos que va a utilizar es buscarte en internet, y es, en este punto donde radica la importancia de contar con una buena reputación online [@huella-digital].

En este sentido es importante en un primer momento, conocer si tu huella digital goza de una buena salud y para ello lo más recomendable es que hagas un ejercicio de búsqueda, para ver si los resultados que obtienes son buenos. Puedes usar algunas de las siguientes herramientas para este propósito:

- Buscar directamente en Google o otros buscadores. Puedes apoyarte en las [búsquedas avanzadas de Google](https://support.google.com/websearch/answer/2466433?hl=es). Esto es lo que se conoce como Egosurfing.

- También tienes plataformas que te ayudan a descubrir dónde están tus datos personales y poder gestionar tu huella digital. En los siguientes enlaces puedes encontrar dos de ellas [Say mine](https://saymine.com/) y [Jumbo privacy](https://www.jumboprivacy.com/).

- Crear alertas de [Google alert](https://www.google.es/alerts). Este recurso también te servira para estar al día de lo que se publica sobre ti.

- [Hootsuite](https://www.hootsuite.com/). Esta herramienta te buscará entre las principales redes sociales, como Facebook, Twitter, etc. es usada en su mayoría en el mundo corporativo.

Si los resultados obtenidos no son de tu agrado, algunas plataformas te permiten solicita la eliminación de dicho contenido o simplemente puedes gestionar tú, esa información desde la propia plataforma. En el caso de Google puedes hacerlo a través de [Mi Actividad](https://myactivity.google.com/myactivity).

Crear una buena huella digital requiere de tiempo y debes ser cuidadoso con la manera en que interactúas en la red. Existen decálogos que te guían para crear una excelente reputación online, así como videos tutoriales y herramientas para llevarlo a cabo. Nos obstante aquí tienes las mejores recomendaciones para cuando quieras compartir, comentar, valorar o opinar en cualquiera de los medios sociales como Facebook, Instagram o cualquier otra, hacer una reseña en Google o participar en algún foro [@decalogo-digital].

- Presencia y actualización sistemática.

- Cuidar la imagen mostrando transparencia.

- Aportar contenido de calidad.

- Respetar siempre la opinión ajena.

- Identificar los canales apropiados con los que interactuar.

- Tener en cuenta las reglas de urbanidad digital, esto consiste en una redacción cuidada y usos de negritas o enlaces de interés.

- Diferenciar entre lo público y lo privado.

Estas últimas puedes tenerlas en cuenta si quieres llevar tu huella digital a un nivel más profesional.

- Disponer de un blog personal.

- Mantener una actitud en la red activa.

- Permanecer atento a las nuevas redes y formas de difusión.

## Sombra digital

Cada foto que subes a Facebook, Instagram, cada mail que mandas, cada comentario o reseña que vas dejando en la web está generando lo ya conoces como huella digital. Hasta aquí todo bien, pero además de este rastro que es más o menos voluntario, también vas dejando otro rastro del que quizá no seas tan consciente, y a este rastro es al que se le conoce como sombra digital.

Ya en 2008 existían métricas que aseguran que la cantidad de información que se tiene de un individuo era mayor a la información creada por el mismo. 

Partiendo de estos preceptos, la sombra digital es la información que queda de nosotros en los diferentes sistemas ya sean públicos o privados. Estos datos nos identifican y saben de nuestros gustos y preferencias. En la mayoría de los casos sin que nosotros mismos seamos conscientes de ello.

En este punto es cuando te estas preguntando como se crea la sombra digital. Pues bien, la sombra digital se va creando con el uso que haces de tus dispositivos, de la cámara en lugares públicos o privados, con el uso de la domótica como en el caso de las bombillas inteligentes y de otras múltiples maneras cuando interactúas con la tecnología. Los fabricantes introducen cookies y software específico para este fin dentro de los sistemas operativos, para saber cuándo los usas, el tiempo que empleas, si usas hardware externo del tipo que sea e incluso para hacer un mapa de tu casa mientras usas tu aspiradora inteligente. Como verás la sombra digital se va construyendo por si sola.

Este concepto podría considerarse como una vulnerabilidad más de tu privacidad, pero también puede ser de mucha utilidad, como por ejemplo, cuando Google maps analiza tu movilidad para gestionar mejor tu trayecto, mostrarte cuánto vas a tardar, que ruta puedes tomar y todo en tiempo real, algo que no sería posible sin la gestión de la sombra digital [@XATAKA-sombra-digital].

## Eliminar el historial de busquedas

Cualquier navegador, salvo que usemos una navegación privada, almacena un registro de las páginas que hemos visitado, una información que podemos borrar si queremos o conservar en el caso de querer localizar más tarde alguna página que no recordemos. Es muy útil en este segundo caso, pero puede llegar a ser embarazoso si no queremos que nadie pueda ver las webs que hemos visitado.

Cada navegador ofrece la posibilidad de borrar toda esta información y para ello puedes acceder desde los menús del propio navegador. Cada navegador tiene una forma diferente de realizar este borrado, aunque normalmente suele estar en la opción/pestaña herramientas. No obstante, el siguiente enlace te llevará a la web del antivirus [AVG](https://www.avg.com/es/signal/how-to-clear-your-browsing-and-search-history), desde donde te enlazará a los diferentes tutoriales de cómo borrar el historial de navegación y de búsquedas de los navegadores más populares, como Google Chrome, Firefox o Microsoft Edge entre otros.

## Derecho al olvido

El Reglamento General de Protección de Datos recoge una norma que permite a los usuarios poder ejercer su derecho al olvido. Esto quiere decir que todas las personas tienen el derecho de solicitar a los buscadores, webs o plataformas que eliminen todos sus datos personales que aparecen en los resultados de búsqueda al introducir un nombre o cualquier otro dato personal. Dicho de otro modo, el derecho al olvido es aquel que tienen todos los ciudadanos a impedir la difusión de información personal a través de Internet.

Cabe aclarar que la eliminación de un enlace de un buscador no implica la desaparición de toda la información de carácter personal publicada en Internet. Este borrado sólo afecta a los motores de búsqueda que enlazan a dicho contenido [@OSI-derecho-al-olvido].

Los siguientes enlaces te llevarán a los formularios de las plataformas detalladas donde podrás solicitar tu derecho al olvido:

-[Solicitud de derecho al olvido de Google](https://support.google.com/websearch/troubleshooter/3111061?hl=es)  

-[Solicitud de derecho al olvido de Bing](https://help.bing.microsoft.com/#apex/18/ES/10013/-1/ES) 

-[Solicitud de derecho al olvido de Yahoo](https://es-us.ayuda.yahoo.com/kb/Eliminaci%C3%B3n-de-resultados-de-b%C3%BAsqueda-de-Yahoo-Search-sln4530.html)

-[Solicitud de derecho al olvido de Facebook](https://www.facebook.com/help/217091804975136) 

Como podrás imaginar estas son las plataformas más relevantes, no obstante, todas las demás deben de tener esta opción. Si la plataforma a la que quieres solicitar tu derecho al olvido no está entre éstas, solicítalo por el canal de comunicación que tengan establecido.

Este derecho se puede gestionar al amparo de la [agencia española de protección de datos](https://www.aepd.es/es/areas-de-actuacion/internet-y-redes-sociales/derecho-al-olvido) y en caso de fallar esta primera vía administrativa siempre nos quedaría la vía judicial.

Esto es parte de lo que se conoce como derecho al olvido. Si quieres más información visita el enlace [¿Sabes cómo ejercer el derecho al olvido?](https://www.osi.es/es/actualidad/blog/2018/09/19/sabes-como-ejercer-el-derecho-al-olvido).
