# Contenido en la red

## El contenido digital

Cada vez más el contenido digital es mayor, a su vez va creciendo de manera exponencial y además está disponible en multitud de formatos, como textos, imágenes, audio, vídeos. Llega a todos los públicos por diferentes canales y an tratándose del mismo contenido, la manera en que este es mapeado o modelado,  también es otra variante más de como la información llega al receptor final. Un ejemplo de como mapear o modelar una misma información en un mismo formato sería el uso de la representación visual o también conocido como Visual Thinking y una infografía, ambos dos están representados en formato imagen.

La lectura que debes hacer en este punto, es que no toda la información vale y no todo el contenido es de calidad, por ello, tener claro los siguientes puntos pueden ser de mucha ayuda.

## Contrastar la información

Según el diccionario de la Real Academia Española, la palabra contrastar en una de sus acepciones consiste en comprobar la exactitud o autenticidad de algo. Hoy en día la información en más rápida de encontrar y abundante en lo que se conoce como infoxicación. La [infoxicación](https://es.godaddy.com/blog/infoxicacion-causas-consecuencias/) no es más que la sobrecarga de información a la que las personas se ven sometidas en su día a día, por lo que es importante saberla escoger, y saber que en muchos casos se trata de información irrelevante que algunas personas comparten simplemente por falta de conocimiento o criterio y en el peor de los casos para confundir.

Al contrastar información debes hacer un análisis de todas aquellas fuentes que encuentras, ya que el resultado de una búsqueda en los navegadores es muy abundante y la información a veces es efímera y puede llegar a no estar totalmente actualizada, con lo que eso conlleva.

No debes conformarte con dar por buena la primera versión de una información en Internet, empobrece tu experiencia como usuario y te perjudica  como lector. Por ello debes tener presente el compromiso ético, por mucho que las prisas sean las que mandes en algunas ocasiones, siempre debes cuidar tu ética al trabajar y contrastar muy bien toda información y fuente [@contrastar-informacion].

## Fake news y Deepfake

Las fake news o también llamados bulos o hoax son noticias sobre temas de interés social o de actualidad para crear una alarma o atraer la atención del mayor número de usuarios posibles y  su objetivo principal es la desinformación. Suelen compartirse por redes sociales, correo electrónico o aplicaciones de mensajería instantánea como WhatsApp que aun contando con una [función antibulos](https://www.osi.es/es/actualidad/blog/2020/04/27/whatsapp-y-su-funcion-antibulos-descubrela) no queda exenta [@OSI-bulos-buenas-practicas].

Se diseñan y emiten con la intención deliberada de engañar, inducir a error, manipular decisiones personales, desprestigiar o enaltecer a una institución, entidad o persona u obtener ganancias económicas o rédito político, aunque en algunas ocasiones también incluyen promociones, ofertas y descuentos, especialmente en época de rebajas o compras navideñas [@WIKI-fake-news].

De otro lado el deepfake es una técnica de inteligencia artificial que permite editar vídeos falsos de personas que aparentemente son reales, dando como resultado final un vídeo muy realista, aunque ficticio [@WIKI-deepfake]. 

Amplia la información sobre deepfake en este artículo [¿Qué es y en qué consiste Deepfake?](https://computerhoy.com/reportajes/tecnologia/consiste-deepfake-446355) de la revista digital Computer Hoy. En este otro artículo llamado [así es posible saber si un vídeo es un deepfake con sólo un abrir y cerrar de ojos](https://www.xataka.com/inteligencia-artificial/posible-saber-video-deepfake-solo-abrir-cerrar-ojos-literalmente-quizas-eso-no-sea-suficiente) tienes un video que no deberías dejar de ver, donde por medio de la inteligencia artificial ponen la cara del actor Steve Buscemi al cuerpo de Jennifer Lawrence en una intervención de una gala. Y por si el anterior video te sabe a poco aquí tienes otro de [deepfake de Barack Obama](https://www.youtube.com/watch?v=cQ54GDm1eL0).

A su vez los deepfakes pueden ser de tipo deepface o deepvoice. El deepface es cuando se trata de una imagen y audio o lo que es lo mismo de un video y el deepvoice cuando solo se trata de la manipulación de la voz.
	
A continuación, verás algunos consejos para poder hacer una buena criba de la información que te encuentres:

- Revisa la URL: mira que se trate de una web legítima.

- Revisa el titular: haz una búsqueda del titular para poder contrastar su autenticidad.

- Contrasta la información en la red: realiza una búsqueda para comprobar la veracidad.  

- Busca la fuente: comprueba si la fuente es legítima.

- Comprueba la autoría: si no aparece el autor es posible que no sea de fiar.

- Comproba el formato: imágenes de poca calidad, redacción con errores gramaticales, faltas de ortografías, portal poco cuidado, etc.

- Revisa la imagen de la noticia: para comprobar que la imagen realmente corresponde con la información y no esta sacada de otra noticia, que además no guarde ninguna relación con esta. Para ello tienes este par de recursos [Google images search](https://www.google.es/imghp?hl=es) y [Tineye](https://tineye.com/).

- Aplica el sentido común.

En el caso de tratarse de una deepfake ten encuenta los siguientes:

- Fíjate en los fondos: fondos desconfigurados o poco fiables.

- Busca deficiencias en los movimientos: movimientos extraños en el personaje.

- Céntrate en los gestos: gestos faciales no naturales o falta de parpadeo, teniendo en cuenta que el ser humano parpadea aproximadamente cada 5 o 10 segundos.

- Agudiza el oído: fallos en el audio o ruidos extraños.

- Mira la duración: al ser caros de editar suelen ser intervenciones breves.

- Reflexiona: piensa si lo que se dice concuerda con los valores e ideales de quién lo dice.

- Aplica de nuevo el sentido común.

En esta entrada de Google llamada [Identifica la información falsa en línea con estos consejos](https://blog.google/products/news/consejos-verificacion-hechos/) encontrarás más consejos para que detectar fake news te resulte más sencillo.

El compartir bulos o fake news aunque no seas consciente de ello fomenta la desinformación, en algunos casos la propagación de virus, malware o cualquier otra amenaza de las que ya conoces y además puede llegar a afectar negativamente a tu reputación digital, sin olvidarnos que afecta a tus contactos y a tu relación con ellos [@OSI-frena-evita-bulos].

Cuando creas que te encuentras ante un posible bulo o fake news, ten en cuentas los siguientes:

- No los reenvíes.

- No abras enlaces ni realices descargas.

- Verifica la información.

En esta lista tienes plataformas que te ayudarán a identificar si estas ante un bulo o fake news:

- [Google Fact Check Explorer](https://toolbox.google.com/factcheck/explorer)

- [Newtral](https://www.newtral.es/zona-verificacion/fact-check/)

- [Maldita](https://maldita.es/malditobulo/1)

- [VerificaRTVE](https://www.rtve.es/noticias/verificartve/)

En la plataforma Maldita, una de las actividades que realizan son la de desenmascarar estos bulos desgranando y dándote claves para que vayas aprendiendo a detectarlos.

## Deep web

El tema de la Deep Web es quizá un tema polémico y estigmatizado, pero al tratarse de una pieza más en este inmenso puzle que es internet, es de recibo conocer al menos de que trata esto de la Web Profunda (Deep Web).
	
Existe una serie de contenido que por diversos motivos no está indexado en los buscadores convencionales como Google, Bing o Yahoo, entre otros y no siempre por temas de legalidad, moralidad o por no ser contenido lícito. Por ejemplo, si estas en china y quieres acceder a Google no te va a quedar otro remedio que hacer uso de este servicio, ya que como sabrás China no permite el uso de Google, entre otros muchos servicios de internet. Es por esto y otras razones por lo que existe la Deep Web [@OSI-deep-web].

De otro lado, está el controvertido tema de las ilegalidades y otros asuntos turbios en lo que se conoce como la Dark Web y de los que no se va a tratar en este manual. Pero si quieres indagar por tu cuenta visita el siguiente enlace [Una semana en la Deep Web y esto es lo que me encontrado](https://www.xataka.com/analisis/una-semana-en-la-deep-web-esto-es-lo-que-me-he-encontrado).
