# Otros conceptos relacionados

##  Otros conceptos que te pueden ayudar

En esta última unidad podrás ver otros aspectos relacionados con la privacidad y seguridad en internet que también te pueden ayudar a abordar todos estos temas.

## Constastar la información

Contrastar es sacar la información más relevante de los diferentes lugares en los que la encontramos, ya que es una idea principal de aquello que necesitamos comprender o aplicar. Hoy en día la información en más rápida de encontrar, por lo cual hay que saberla escoger, porque en muchos casos son cosas irrelevantes que las personas ponen solo para confundir o simplemente por falta de conocimiento o criterio.

Al contrastar información debes hacer un análisis de todas aquellas fuentes de información que encuentras, ya que los resultados de búsquedas en los navegadores es muy abundante y la información a veces es efímera y puede llegar a no estar totalmente actualizada, con lo que eso conlleva.

No debemos conformarnos con dar por buena la primera versión de una información en Internet, empobrece nuestra experiencia como usuarios, nos perjudica a nosotros los lectores. Por ello hay que tener presente el compromiso ético, por mucho que las prisas sean las que mandes en algunas ocasiones, siempre debemos cuidar nuestra ética al trabajar y contrastar muy bien toda información y fuente [@contrastar-informacion].
   
## Otras utilidades interesantes

Aparte de todo lo visto en el manual existen muchas otras herramientas para ayudarnos a salvaguardar nuestra privacidad y seguridad en la red, algunas de estas son:

- Emails temporales: [Temporay email](https://temp-mail.org/es/). Si solo necesitas regístrarte en una web para un recurso puntual, como por ejemplo descargarte un eBook, puedes hacer uso de este servicio. Y si usas el navegador Firefox, podrás tener este mismo servicio integrado en el propio navegador con solo la instalación de un plugin [Relay firefox](https://relay.firefox.com). 

- Escaneo de URLs maliciosas: [UrlScan](https://urlscan.io/). Esta plataforma detecta las direcciones webs fraudulentas.

- Comprobar y mejorar tu privacidad y seguridad en internet: [Lista de verificación de seguridad](https://securitycheckli.st/). Esta web esta en inglés pero abarca un amplio espectro de herramientas y recursos diseñados para mejorar tu privacidad, seguridad y protección online y siempre dispones del traductor en línea de google.

- Eliminar cuentas en Redes Sociales: [Deseat](https://www.deseat.me/).  Con esta plataforma podrás tener instantáneamente una lista de todas tus cuentas y eliminar las que no estés usando o las que te apetezcan. 
 
- Números de teléfono de usar y tirar: [Hushed](https://hushed.com). Se trata de un servicio premiun pero de coste muy económico. Solo es cuestión de ver si te compensa. 

- Nombres y direcciones desechables: [Generador de nombres falsos](https://www.fakenamegenerator.com). Como en el caso de los emails temporales este servicio puede ser un buen recurso.

## Entidades e instuciones de ayuda al ciudadano

**INSTITUTO NACIONAL DE CIBERSEGURIDAD** [INCIBE](https://www.incibe.es/)

El Instituto Nacional de Ciberseguridad de España (INCIBE), es una sociedad dependiente del Ministerio de Economía y Empresa a través de la Secretaría de Estado para el Avance Digital y consolidada como entidad de referencia para el desarrollo de la ciberseguridad y de la confianza digital de ciudadanos, red académica y de investigación, profesionales, empresas y especialmente para sectores estratégicos.

La misión de INCIBE es por tanto reforzar la ciberseguridad, la confianza y la protección de la información y privacidad en los servicios de la Sociedad de la Información, aportando valor a ciudadanos, empresas, Administración, red académica y de investigación española, sector de las tecnologías de la información y las comunicaciones y sectores estratégicos en general. Aunándolo es estas tres siguientes líneas de actuación:

- Al internauta.

- Al menor.

- A la empresa.

Informan entre otros sobre: 

- Protección de redes, equipos y sistemas.

- Cumplimiento de obligaciones relativas a la seguridad de la información.

- Diferentes tipos de incidentes de seguridad.

- Seguridad en las conexiones y redes wifi.

-  Configuración de la privacidad en dispositivos y servicios de internet.

- Situaciones de infección por virus.

- Contenidos inadecuados para menores y comunidades peligrosas en línea.

- Ciberacoso escolar.

- Controles parentales.

Dispone de un teléfono gratuito 017.    

**OFICINA DE SEGURIDAD DEL INTERNAUTA** [OSI](https://www.osi.es/es)

Hola

**AGENCIA ESPAÑOLA DE PROTECCIÓN DE DATOS** [AEPD](https://www.aepd.es/es)

Hola

En caso de tratarse de menores

**PANTALLAS AMIGAS** [Pantallasamigas.net](https://www.pantallasamigas.net/)

Para menores

**INTERNET SEGURA PARA NIÑOS** [is4k](https://www.is4k.es/)

Para niños



