# Otras particularidades importantes

##  Otros conceptos relevantes

Existen otras muchas particularidades y conceptos que al no encajar de  manera directa en unidades anteriores van a ser vistas en esta unidad. Aquí podrás ver otros aspectos relacionados con la privacidad y seguridad en internet que también te pueden ayudar a abordar todos estos temas.

## Desinfecta tu dispositivo

Si crees que tu dispositivo puede estar infectado, aquí tienes una entrada de la Oficina de Seguridad de Internauta llamada [desinfecta tu dispositivo](https://www.osi.es/es/desinfecta-tu-ordenador), encabezada con los principales signos que pueden ponerte sobre aviso, así como las 3 fases de las que consta para solucionar este contratiempo y que son, una primera fase de primeros auxilios, una segunda fase de soluciones avanzadas y una tercera y última fase de solución definitiva.

## Menores en el uso de la red

En lo que concierne a menores, la cuestión se torna más delicada, ya que se trata de grupo más inexperto y vulnerable. En este manual no se va a tratar en profundidad este tema, ya que por si solo podría tratarse de otro manual completo, pero si cabe destacar algunos conceptos bastantes relevales como la educación, la concienciación y el seguimiento que tú, como padre, madre o tutor debes hacer del uso que hacen los menores de internet.

Por supuesto también has de conocer y hacerles saber de los peligros y amenzas con las que pueden encontrarse y que asechan tras la aparente inofensiva pantalla.

Sabes que entre el uso que hacen tus hijos de la red están actividades lúdicas como jugar, otras didácticas como aprender, otras sociales como relacionarse con amigos u otros y todo ésto, en la mayoría de la veces a tan solo solo click. 

Pero no olvides que debes ser tú quien los guíe en la educación y concienciación, además de hacer un seguimiento de cerca para saber el uso que hace de las tecnologías. Para todo esto dispones de guías, herramientas, consejos, etc. Cabe destacar que es importante guiarlos para que tus menores hagan un uso responsable, respetuoso y de carácter prudente en el ámbito tecnológico, y que a su vez sean conscientes de todas las particularidades que conlleva interactuar tanto con los medios como con los dispositivos.

Por todo lo anteriormente expuesto, a continuación tienes estas sucintas listas como toma de contacto en lo que a menores se refiere.

Medidas con las que los menores deben comprometerse:
 
- No publicar fotos o vídeos de alguien sin permiso. (Válido también para adultos). 

- No usar la webcam con desconocidos. (Existen adesivos para taparla).

- No creer en los regalos o chollos. (Ventanas pop-up - emails ...).

- No aceptar amigos en la redes sociales que no conozcan. (No son amigos reales).

- No ponerse en contacto con desconocidos. 

- No acordar citas con desconocidos a través de internet.

- No facilitar datos personales. (Se sentirán más protegido/as).

- No contestar a las provocaciones, ignóralas.
	
- No hacer en la Red lo que no harían a la cara.

- Tener cuidado con la información que comparten en línea. (incluyendo el correo, redes sociales como Instagram, TikTok…).

- Comportarse con educación en la Red.

- Respetar los derechos de los demás en Internet. (No se debe reenviar material inadecuado por correo electrónico).

- Si los molestan o  amenazan, deben abandonar la conexión y pedir ayuda.

- Mostrarse más celoso de su vida privada. (No diferencian bien entre público y privado, acostumbran a sociabilizar todos los aspectos de su vida).

Principales amenazas a la que los menores están expuestos:

- [Ciberbylling](https://ayudaenaccion.org/ong/blog/educacion/ciberbullying/).

- [Gossip o informer](https://educacion2.com/que-es-el-fenomeno-gossip-e-informer/).

- [Ciberadicción](https://www.aepap.org/sites/default/files/pags._131-142_ciberadicciones.pdf).

- [Vamping](https://www.educapeques.com/escuela-de-padres/vamping-definicion.html).

- [Grooming](https://www.is4k.es/necesitas-saber/grooming).

- [Sexting](https://www.is4k.es/menores-y-sexting).

Además conforme vayan creciendo se podrán ir topando con todos los peligros anteriormente vistos en este manual.

Qué debes enseñar a tus hijos como padre, madre o tutor:

- Concienciar a los menores sobre su actividad en la red. Aquello que salga de su móvil o correo no podrá recuperarlo jamás, perdurará en el tiempo y se trata de una  información personal que cualquiera podría utilizarla.

- Hacerles concientes de su identidad digital

- Deben entender que navegar por Internet puede considerarse un derecho, pero también supone una responsabilidad. (Al igual que pasear por la calle no les da derecho a cruzar con un semáforo en rojo, navegar por  Internet no les da derecho a entrar en un lugar que no deben).

- Contraseñas seguras y diferentes. En la unidad de Gestión de la seguridad en la red de este manual encontrarás en el apartado de contraseñas todo lo que necesitas saber.

- Es fácil deducir información personal de fotos o comentarios. (Lugar donde vive, los sitios que se frecuentas...).

- Enséñale a no hacer descargar programas sin tu permiso.(, música o archivos - propiedad intelectual, programas con virus, malware en naveradores...).

- Ayudar y enseñarles a protegerlos del spam. (Correos phising, software espia, malware...).

- Alertar a los menores que deben avisarles siempre  que algún "amigo de Internet" insista respecto a informaciones o hábitos personales.

- Deben saber que no están del todo seguro/a al otro lado de la pantalla. 

- El riesgo es el mismo en el mundo digital que en el real.

- No toda la información en internet es veraz o fidedigna. (Contrastar varias fuentes).

Cuál es tu compromiso como padre, madre o tutor:

- Establecer espacios de trabajo independientes: es bueno que nuestros hijos tengan su propio espacio dentro del ordenador: su propio escritorio, su propio fondo de pantalla, su propia lista de favoritos, su  propio sistema   de carpetas.  (De esa manera protegemos nuestros datos y les hacemos responsables de los suyos, pudiendoles crear un [control parental](https://securekids.es/que-es-el-control-parental-y-para-que-sirve/) o restricciones mediante el navegador y apps para  dispositivos móviles).

- Establecer un  horario de tiempo máximo de conexión.

- Colocar el ordenador en una zona común.

- Navegar por internet solo en presencia de un adulto. (Para que no crezcan como huerfanos digitales).

- Estar informados del tipo y tiempo de navegación que hacen.

- Manténganse actualizados con la tecnología. (No necesitas saber exactamente como funcionan todo, sólo necesitas saber qué son y para qué se usan. Ejemplo: no es lo mismo un chat que una app de mensajería instantánea.

- Hablar habitualmente de las tecnologías y compartir actividad digital con ellos. (Respecto a la "navegación" que  practican, a respetar las reglas y cumplir con obligaciones y acuerdos, a negociar y dialogar sobre los límites  “Reglas consensuadas" para navegar en Internet).

- Fomentar y premiar el uso adecuado y responsable de las tecnologías.

- Disponer de antivirus.

- Conocer el código PEGI (Pan European Game Information) que regula los juegos, donde se estipulan si con de carácter individual o colectivo, de estrategías, deportivos, shooting, aventura, etc.

Para ampliar la información dispones de dos exhaustivas guías de la Junta de andalucia [Guía de formación TIC para padres y madres de menores de 3 a 11 años](https://www.andaluciaesdigital.es/documents/20182/28716/Educar+para+Proteger+-+Guía+resumida+de+formación+TIC+para+padres+y+madres+de+niños+de+3+a+11+años.pdf) y [Guía de formación TIC para adolescentes](https://www.juntadeandalucia.es/educacion/portalaverroes/documents/10306/1673096/Educar_para_proteger_Guia_Adolescentes.pdf).

Y en estos dos enlaces encontrarás dos prácticos recursos [Family Link by Google](https://families.google.com/familylink/) y [Secure Kids](https://securekids.es/).

## Utilidades interesantes

Aparte de todo lo visto en el manual existen muchas otras herramientas para ayudarnos a salvaguardar nuestra privacidad y seguridad en la red, algunas de estas son:

- Emails temporales: [Temporay email](https://temp-mail.org/es/). Si solo necesitas regístrarte en una web para un recurso puntual, como por ejemplo descargarte un eBook, puedes hacer uso de este servicio. Y si usas el navegador Firefox, podrás tener este mismo servicio integrado en el propio navegador con solo la instalación de un plugin [Relay firefox](https://relay.firefox.com). 

- Escaneo de URLs maliciosas: [UrlScan](https://urlscan.io/). Esta plataforma detecta las direcciones webs fraudulentas.

- Comprobar y mejorar tu privacidad y seguridad en internet: [Lista de verificación de seguridad](https://securitycheckli.st/). Esta web esta en inglés pero abarca un amplio espectro de herramientas y recursos diseñados para mejorar tu privacidad, seguridad y protección online y siempre dispones del traductor en línea de google.

- Eliminar cuentas en Redes Sociales: [Deseat](https://www.deseat.me/).  Con esta plataforma podrás tener instantáneamente una lista de todas tus cuentas y eliminar las que no estés usando o las que te apetezcan. 
 
- Números de teléfono de usar y tirar: [Hushed](https://hushed.com). Se trata de un servicio premiun pero de coste muy económico. Solo es cuestión de ver si te compensa. 

- Nombres y direcciones desechables: [Generador de nombres falsos](https://www.fakenamegenerator.com). Como en el caso de los emails temporales este servicio puede ser un buen recurso.

## Eventos internacionales 

Dia internacional de internet seguro 

Día mundial de la contraseña

## Colabora

¿Cómo colaborar?

