# Otras particularidades importantes

##  Otros conceptos relevantes

Existen otras muchas particularidades y conceptos que al no encajar de  manera directa en unidades anteriores van a ser vistas en esta unidad. Aqu칤 podr치s ver otros aspectos relacionados con la privacidad y seguridad en internet que tambi칠n te pueden ayudar a abordar todos estos temas.

## Desinfecta tu dispositivo

Si crees que tu dispositivo puede estar infectado, aqu칤 tienes una entrada de la Oficina de Seguridad de Internauta llamada [desinfecta tu dispositivo](https://www.osi.es/es/desinfecta-tu-ordenador), encabezada con los principales signos que pueden ponerte sobre aviso, as칤 como las 3 fases de las que consta para solucionar este contratiempo y que son, una primera fase de primeros auxilios, una segunda fase de soluciones avanzadas y una tercera y 칰ltima fase de soluci칩n definitiva.

## Menores en el uso de la red

En lo que concierne a menores, la cuesti칩n se torna m치s delicada, ya que se trata de grupo m치s inexperto y vulnerable, siendo 1 de cada 3 usuarios de internet un ni침o. En este manual no se va a tratar en profundidad este tema, ya que por si solo podr칤a tratarse de otro manual completo, pero si cabe destacar algunos conceptos bastantes relevantes como la educaci칩n, la concienciaci칩n y el seguimiento que t칰, como padre, madre o tutor debes hacer del uso que hacen los menores de internet.

Por supuesto tambi칠n has de conocer y hacerles saber de los peligros y amenazas con las que pueden encontrarse y que asechan tras la aparente inofensiva pantalla.

Sabes que entre el uso que hacen tus hijos de la red est치n actividades l칰dicas como jugar, otras did치cticas como aprender, otras sociales como relacionarse con amigos u otros y todo esto, en la mayor칤a de las veces a tan solo solo click. 

Pero no olvides que debes ser t칰 quien los gu칤e en la educaci칩n y concienciaci칩n, adem치s de hacer un seguimiento de cerca para saber el uso que hace de las tecnolog칤as. Para todo esto dispones de gu칤as, herramientas, consejos, etc. Cabe destacar que es importante guiarlos para que tus menores hagan un uso responsable, respetuoso y de car치cter prudente en el 치mbito tecnol칩gico, y que a su vez sean conscientes de todas las particularidades que conlleva interactuar tanto con los medios como con los dispositivos.

Por todo lo anteriormente expuesto, a continuaci칩n, tienes estas sucintas listas como toma de contacto en lo que a menores se refiere.

Medidas con las que los menores deben comprometerse:
 
- No publicar fotos o v칤deos de alguien sin permiso. Esto tambi칠n hay que tenerlo en cuenta entre adultos. 

- No usar la webcam con desconocidos. Adem치s de tenerla tapada cuando no se est칠 usando, para ello existen adhesivos y otros artilugios.

- No creer en los regalos o chollos a los que se ver치n expuestos a trav칠s de ventanas pop-up, emails, etc.

- No aceptar amigos en las redes sociales que no conozcan, ya que en un principio no los deber칤an considerar como amigos reales.

- No ponerse en contacto con desconocidos. 

- No acordar citas con desconocidos a trav칠s de internet.

- No facilitar datos personales.

- No contestar a las provocaciones e ignorarlas.
	
- No hacer en la Red lo que no har칤an a la cara.

- Tener cuidado con la informaci칩n que comparten en l칤nea, incluyendo el correo, redes sociales como Instagram, TikTok, etc.

- Comportarse con educaci칩n en la Red.

- Respetar los derechos de los dem치s en Internet y no reenviar material inadecuado por correo electr칩nico o cualquier otra plataforma de difusi칩n.

- Si los molestan o  amenazan, deben abandonar la conexi칩n y pedir ayuda.

- Mostrarse m치s celoso de su vida privada. Ya que llega un punto en que no diferencian bien entre lo p칰blico y lo privado y acostumbran a sociabilizar todos los aspectos de su vida.

Principales amenazas a la que los menores est치n expuestos:

- [Ciberbylling](https://ayudaenaccion.org/ong/blog/educacion/ciberbullying/).

- [Gossip o informer](https://educacion2.com/que-es-el-fenomeno-gossip-e-informer/).

- [Ciberadicci칩n](https://www.aepap.org/sites/default/files/pags._131-142_ciberadicciones.pdf).

- [Vamping](https://www.educapeques.com/escuela-de-padres/vamping-definicion.html).

- [Grooming](https://www.is4k.es/necesitas-saber/grooming).

- [Sexting](https://www.is4k.es/menores-y-sexting).

- [Obesidad digital](https://www.levantalacabeza.es/obesidad-digital/).

Adem치s, conforme vayan creciendo se podr치n ir topando con todos los peligros anteriormente vistos en este manual.

Qu칠 debes ense침ar a tus hijos como padre, madre o tutor:

- Concienciarles sobre su actividad en la red. Aquello que salga de su m칩vil o correo no podr치 recuperarlo jam치s, perdurar치 en el tiempo y se trata de una  informaci칩n personal que cualquiera podr칤a utilizarla.

- Hacerles conscientes de su identidad digital.

- Deben entender que navegar por Internet puede considerarse un derecho, pero tambi칠n supone una responsabilidad. Al igual que pasear por la calle no les da derecho a cruzar con un sem치foro en rojo, navegar por  Internet no les da derecho a entrar en un lugar que no deben.

- Contrase침as seguras y diferentes. En la unidad de Gesti칩n de la seguridad en la red de este manual encontrar치s en el apartado de contrase침as todo lo que necesitas saber.

- Deben saber que es f치cil deducir informaci칩n personal de fotos o comentarios, como por ejemplo el lugar donde viven, los sitios que frecuentan y dem치s.

- Ens칠침ales a no hacer descargas de programas sin tu permiso, para que sepan en que consiste la propiedad intelectual y a tener cuidado con programas con virus, etc.

- Ayudarles y ense침arles a protegerse del spam, correos phising, software esp칤a, malware, etc.

- Alertar a los menores que deben avisarte siempre  que alg칰n "amigo de Internet" insista respecto a informaciones o h치bitos personales.

- Deben saber que no est치n del todo seguro/a al otro lado de la pantalla. 

- El riesgo es el mismo en el mundo digital que en el real.

- Ay칰dalos a entender que no toda la informaci칩n en internet es veraz o fidedigna, y que la informaci칩n debe contrastarse en varias fuentes.

Cu치l es tu compromiso como padre, madre o tutor:

- Establecer espacios de trabajo independientes. Es bueno que tus hijos tengan su propio espacio dentro del ordenador, su propio escritorio, su propio fondo de pantalla, su propia lista de favoritos, su  propio sistema   de carpetas.  De esa manera proteges tus datos y les haces responsables de los suyos, pudi칠ndoles crear un [control parental](https://securekids.es/que-es-el-control-parental-y-para-que-sirve/) o restricciones mediante el navegador y apps para  dispositivos m칩viles.

- Establecer un  horario de tiempo m치ximo de conexi칩n.

- Colocar el ordenador en una zona com칰n.

- Navegar por internet solo en presencia de un adulto. De esta manera no crecer치n como hu칠rfanos digitales.

- Estar informado del tipo y tiempo de navegaci칩n que hacen.

- Mantente actualizado con la tecnolog칤a. No necesitas saber exactamente como funciona todo, s칩lo necesitas saber qu칠 son y para qu칠 se usan. Ejemplo: no es lo mismo un chat que una app de mensajer칤a instant치nea.

- Hablar habitualmente de las tecnolog칤as y compartir actividad digital con ellos. Respecto a la navegaci칩n que  practican, a respetar las reglas y cumplir con obligaciones y acuerdos, a negociar y dialogar sobre los l칤mites  (Reglas consensuadas) para navegar en Internet.

- Fomentar y premiar el uso adecuado y responsable de las tecnolog칤as.

- Disponer de antivirus.

- Conocer el c칩digo PEGI (Pan European Game Information) que regula los juegos, donde se estipulan si son de car치cter individual o colectivo, de estrategias, deportivos, shooting, aventura, la edad adecuada de consumo, etc.

Para ampliar la informaci칩n dispones de dos exhaustivas gu칤as de la Junta de Andalucia [Gu칤a de formaci칩n TIC para padres y madres de menores de 3 a 11 a침os](https://www.andaluciaesdigital.es/documents/20182/28716/Educar+para+Proteger+-+Gu칤a+resumida+de+formaci칩n+TIC+para+padres+y+madres+de+ni침os+de+3+a+11+a침os.pdf) y [Gu칤a de formaci칩n TIC para adolescentes](https://www.juntadeandalucia.es/educacion/portalaverroes/documents/10306/1673096/Educar_para_proteger_Guia_Adolescentes.pdf).

Y en estos dos enlaces encontrar치s dos pr치cticos recursos [Family Link by Google](https://families.google.com/familylink/) y [Secure Kids](https://securekids.es/).

## Utilidades interesantes

Aparte de todo lo visto en el manual existen muchas otras herramientas para ayudarte a salvaguardar tu privacidad y seguridad en internet, algunas de estas son:

- Correo electr칩nico (email): 

    - Emails temporales: Si solo necesitas registrarte en una web para un recurso puntual, como por ejemplo descargarte un eBook, puedes utilizar [Temporay email](https://temp-mail.org/es/) y no es el 칰nico servicio de este tipo, en el siguiente enlace tienes una lista m치s amplia de [servicios de correos temporales](https://www.genbeta.com/correo/7-servicios-de-email-temporales-para-evitar-spam-y-otros-problemas). Y si usas el navegador Firefox, podr치s tener este mismo servicio integrado en el propio navegador con solo la instalaci칩n del plugin [Relay firefox](https://relay.firefox.com). 
    
    - Emails an칩nimos: Con [Secure email](https://www.secure-email.org/index.php) puedes enviar correos electr칩nicos y SMS an칩nimos, falsificar el n칰mero del remitente de SMS y muchos m치s.
    
    - Modificar el alias o identidad del email: [Simple login](https://simplelogin.io/) es un servicio con el que puedes crear tus alias o identidades para ocultar tu email personal, evitar spam y mantener tu privacidad.
    
- Escaneo de URLs maliciosas: [UrlScan](https://urlscan.io/). Esta plataforma detecta las direcciones webs fraudulentas.

- Comprobar y mejorar tu privacidad y seguridad en internet: [Lista de verificaci칩n de seguridad](https://securitycheckli.st/). Esta web esta en ingl칠s, pero abarca un amplio espectro de herramientas y recursos dise침ados para mejorar tu privacidad, seguridad y protecci칩n online y siempre dispones del traductor en l칤nea de Google.

- Eliminar cuentas en Redes Sociales: [Deseat](https://www.deseat.me/) es una plataforma con la que podr치s tener instant치neamente una lista de todas tus cuentas y eliminar las que no est칠s usando o las que te apetezcan. 
 
- N칰meros de tel칠fono de usar y tirar: [Hushed](https://hushed.com) es un servicio premium pero de coste muy econ칩mico. Solo es cuesti칩n de ver si te compensa. 

- Nombres y direcciones desechables: [Generador de nombres falsos](https://www.fakenamegenerator.com). Como en el caso de los emails temporales este servicio puede ser un buen recurso.

- Aviso de webs sospechosas: En el Chrome Web Store encontrar치s este plugin que se llama [Suspicious Site Reporter](https://chrome.google.com/webstore/detail/suspicious-site-reporter/jknemblkbdhdcpllfgbfekkdciegfboi) y que se encargar치 de avisarte si estas ante una web de dudosa reputaci칩n.

- Aviso de actividades sospechosas: Con [Get Logdog](https://getlogdog.com/) recibir치s alertas cada vez que ocurra una actividad sospechosa en tu Gmail, Facebook y otras cuentas.

- Protecci칩n dispositivo m칩vil: [Conan Mobile](https://www.osi.es/es/conan-mobile) te permite conocer el estado de seguridad de tu dispositivo, mostr치ndote soluciones a posibles riesgos a los que est칠s expuesto y proporcion치ndote algunos consejos que te ayudar치n a mejorar su seguridad.

- Verificadores de URLs acortadas: Comprobar la seguridad de una URL acortada antes de hacer click en ella es otra buena pr치ctica para no acabar en una web de dudosa procedencia. A continuaci칩n, tienes estos dos verificadores [Unshorten](https://unshorten.it/), [Checkshorturl](https://checkshorturl.com/) y [VirusTotal](https://www.virustotal.com/gui/home/url) . 

- Plugin o extensi칩n antimalware: [MyWot](https://www.mywot.com/) te mantendr치 a salvo de estafas, malware, phishing y robo de identidad mientras navegas.

- Centros de Seguridad. Estos centros son los servicios con los que las grandes plataformas digitales se comprometen a velar por tu privacidad y seguridad:

    - [Google](https://safety.google).	
    
    - [Facebook](https://es-es.facebook.com/safety).
    
    - [Instagram](https://about.instagram.com/es-la/community/safety).
    
    - [Tiktok](https://www.tiktok.com/safety?lang=es).
    
- Testigos online: Los [testigos online](https://www.osi.es/es/actualidad/blog/2022/01/26/testigos-online-y-obtencion-de-pruebas-te-explicamos-su-utilidad) te permiten certificar evidencias digitales en una fecha y hora determinada, o lo que es lo mismo, el contenido de una web concreta en un momento determinado, o el env칤o de un correo electr칩nico a una persona espec칤fica. 


## Eventos internacionales 

Durante el a침o, pa칤ses e instituciones como la Comisi칩n europea promueven iniciativas entorno al ecosistema tecnol칩gico. Son organizadas a nivel internacional y donde pueden llegar a participar hasta m치s de 100 pa칤ses. En la siguiente lista se muestran las de m치s repercusi칩n medi치tica::

- [D칤a de Internet](https://es.wikipedia.org/wiki/D칤a_de_Internet) (17 de mayo).

- [D칤a Internacional de Internet Segura](https://es.wikipedia.org/wiki/D칤a_Internacional_de_Internet_Segura) (Segundo martes de febrero). 

- [D칤a mundial de la contrase침a](https://es.wikipedia.org/wiki/D칤a_mundial_de_la_contrase침a) (Primer jueves de mayo).

## Colabora

Si eres una persona participativa y te gusta colaborar y aportar a los dem치s. M치s abajo encontrar치s una lista de actividades que podr치s realizar, en las que no solo estar치s ayudando a divulgar contenido y ayudar a otros, sino que adem치s, repercutir치 de manera positiva en tu vida.

- [Cibercooperante](https://www.incibe.es/cibercooperantes/quiero-ser-cibercooperante) (Incibe).

- [Cibervoluntario](https://www.cibervoluntarios.org/) (Ciber voluntarios).

- [Voluntario digital](https://ayudaenaccion.org/ong/colabora/voluntariado-digital/) (Ayuda en acci칩n).

- [Voluntariado digital](https://twitter.com/Clicka_CRE) (Click_A).

AN칈MATE!!! 游땔

